import { config } from "dotenv";

config();

export const {
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  POSTGRES_DB_TEST,
  POSTGRES_HOST,
  POSTGRES_PORT,

  ADMIN_ID,
  DOCTOR_ID,
  GUEST_ID,
  JWT_SECRET_KEY,
  JWT_SECRET_KEY_REFRESH,

  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_MAX_FILESIZE,

  PORT,
  NODE_ENV,
} = process.env;
