name: Server CI

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: supersecretpassword
          POSTGRES_DB: optimabalita_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Migrate database
        run: npm run db:refresh:test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD_TEST: supersecretpassword
          POSTGRES_DB_TEST: optimabalita_test
          POSTGRES_HOST_TEST: localhost
          POSTGRES_PORT_TEST: 5432
          ADMIN_ID: a1582ba5-d764-4a15-b181-657e8753869b
          DOCTOR_ID: 9c4e9a57-12da-4dae-b2e0-edec77c4f86e
          GUEST_ID: 8cb07c50-0735-4df8-8e51-8f15c3fb3a5d
      - name: Run tests
        run: npm run test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD_TEST: supersecretpassword
          POSTGRES_DB_TEST: optimabalita_test
          POSTGRES_HOST_TEST: localhost
          POSTGRES_PORT_TEST: 5432